version: 2.1

commands:
  build_cmd:
    steps:
      - run: ./scripts/build.sh mweb

  custom_build:
    steps:
      - run:
          name: "Hello World"
          command: |
            touch $BASH_ENV
            echo "export STEP_BUILD=123 >> $BASH_ENV"
            source $BASH_ENV
            echo "Start job build"
            cat $BASH_ENV

jobs:
  test:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - build_cmd

  build:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - custom_build

workflows:
  version: 2
  Example_Workflow:
    jobs:
      - test:
          context: build
      - build:
          context: build
          filters:
            branches:
              only:
                - test
          requires:
            - test
