version: 2.1

commands:
  custom_test:
    steps:
      - run:
          name: "Run custom test"
          command: |
            echo "Running custom test"

  custom_build:
    parameters:
      app_name:
        type: string
    steps:
      - checkout
      - run:
          name: "Should build << parameters.app_name >>"
          command: |
            build="build_<< parameters.app_name >>"
            buildPattern= $(git show-branch --no-name HEAD) | head -n1 | awk '{print $1;}'
            echo ${build}
            echo ${buildPattern}
            case ${buildPattern} in
            $build)
              echo "YES:: Trigger build ${build}"
              ;;
            "build_app")
              echo "YES:: Tigger build ${build}"
              ;;
            *)
              echo "No:: SAVE MY TIME, PLEASE STOP"
              circleci-agent step halt
              ;;
              esac
      - run:
          name: "Tigger build << parameters.app_name >>"
          command: |
            echo "Start build << parameters.app_name >>"

jobs:
  test:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
  build:
    parameters:
      app_name:
        type: string
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - custom_build:
          app_name: << parameters.app_name >>

workflows:
  version: 2
  process_cicd:
    jobs:
      - build:
          app_name: mweb
