version: 2.1

commands:
  build_cmd:
    steps:
      - run: ./scripts/build.sh mweb

  custom_build:
    steps:
      - run:
          name: "Hello World"
          command: |
            echo "Start job build"
            echo "${BUILD_STEP}"
            echo ${BUILD_STEP}
jobs:
  test:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - build_cmd

  build:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - custom_build

workflows:
  version: 2
  Example_Workflow:
    jobs:
      - test
      - build:
          filters:
            branches:
              only:
                - test
          requires:
            - test
