version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:12.14.1
        steps:
            - checkout
            - run: yarn
            - run: yarn test

workflows:
    version: 2.1

    run_test:
        jobs:
            - build
