version: 2.1

commands:
  build:
    steps:
      - checkout
      - run:
          name: "Start command build"
          command: |
            echo "Custom test run"
            yarn cache clean -f
            yarn

  test:
    parameters:
      app_name:
        type: string
    steps:
      - checkout
      - run:
          name: "Start command test"
          command: |
            echo "Custom test run"
            yarn test
            echo "Custom comment << parameters.app_name >>"


jobs:
  build:
    docker:
        - image: circleci/node:12.14.1
    steps:
      - checkout
      - run:
          name: "Hello World"
          command: |
              echo "Start job build"
      - build:
          app_name: "BUILD_APP_NAME"

  test:
    docker:
        - image: circleci/node:12.14.1
    steps:
      - checkout
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo 'Start Job test'
      - test:
          app_name: "TEST_APP_NAME"

workflows:
 version: 2
 Example_Workflow:
   jobs:
     - test
     - build:
         requires:
           - test
