version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:12.14.1
        steps:
            - checkout
            - run: yarn
            - run: yarn test
    run:
        docker:
            - image: circleci/node:12.14.1
        step:
            - run: node index.js


workflows:
    version: 2.1

    tbox_test:
        jobs:
            - build
    tbox_run:
        jobs:
            - run
