version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:12.14.1
        steps:
            - checkout
            - run: yarn
            - run: yarn test
    build1:
        docker:
            - image: circleci/node:12.14.1
        steps:
            - checkout
            - run: yarn
            - run: yarn test
    optimize:
        docker:
            - image: circleci/node:12.14.1
        steps:
            - checkout
            - run: node index.js
    optimize1:
        docker:
            - image: circleci/node:12.14.1
        steps:
            - checkout
            - run: node index.js
    optimize2:
        docker:
            - image: circleci/node:12.14.1
        steps:
            - checkout
            - run: node index.js


workflows:
    version: 2.1

    tbox_test:
        jobs:
            - build
            - build1:
                rquires:
                    - build
            - optimize:
                requires:
                    - build
