version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - custom_build

  test:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - custom_test:
          app_name: "TEST_APP_NAME"
      - custom_test:
          app_name: "TEST_APP_NAME2"

workflows:
  version: 2
  Example_Workflow:
    jobs:
      - test
      - build:
          filters:
            branches:
              only:
                - test
          requires:
            - test
