version: 2.1

commands:
  custom_test:
    steps:
      - run:
          name: "Run custom test"
          command: |
            echo "Running custom test"

  custom_build:
    parameters:
      app_name:
        type: string
        app_name: BUILD_ALL
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - run: ./scripts/build.sh << parameters.app_name >>
      - run:
          name: "Tigger build << parameters.app_name >>"
          command: |
            echo "Start build << parameters.app_name >>"

jobs:
  test:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - should_build:
          app_name: BUILD_MINIAPP
      - should_build:
          app_name: BUILD_MWEB
      - custom_test
  build:
    parameters:
      app_name:
        type: string
        app_name: BUILD_ALL
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - should_build:
          app_name: << parameters.app_name >>

workflows:
  version: 2
  process_cicd:
    jobs:
      - test
      - custom_build:
          app_name: BUILD_MWEB
          requires:
            - test
      - custom_build:
          app_name: BUILD_MINIAPP
          requires:
            - test
