version: 2.1

commands:
  should_build:
    steps:
      - run:
          name: "check Should build"
          command: |
            ./scripts/build.sh

  custom_test:
    steps:
      - run:
          name: "Run custom test"
          command: |
            echo "Running custom test"

  custom_build:
    steps:
      - run:
          name: "Hello World"
          command: |
            echo "start build"

jobs:
  test:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - custom_test

  build:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - should_build
      - custom_build

workflows:
  version: 2
  Example_Workflow:
    jobs:
      - test
      - build:
          filters:
            branches:
              only:
                - test
          requires:
            - test
