version: 2.1

commands:
  should_build:
    steps:
      - run:
          name: "check Should build"
          command: |
            ./scripts/build.sh

  custom_test:
    steps:
      - run:
          name: "Run custom test"
          command: |
            echo "Running custom test"

  custom_build:
    steps:
      - run:
          name: "Hello World"
          command: |
            echo "start build"

jobs:
  deploy:
    docker:
      - image: circleci/node:12.14.1
    parameters:
      factor:
        type: string
        default: mobile
      label:
        type: string
        default: Lighthouse Mweb Mobile
      urls:
        type: string
        default: https://mweb.ticketbox.dev
    steps:
      - run:
          name: "Deploy app"
          command: |
            echo "<< parameters.factor >>"
            echo "<< parameters.label >>"
            echo "<< parameters.urls >>"
  test:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - custom_test

  build:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - should_build
      - custom_build

workflows:
  version: 2
  Example_Workflow:
    jobs:
      - test
      - build:
          filters:
            branches:
              only:
                - test
          requires:
            - test
      - deploy:
          factor: "factor1"
          label: "label1"
          urls: "url1"

      - deploy:
          factor: "factor2"
          label: "label2"
          urls: "url2"
